DEFAULT_CATEGORIES = [
    "Biżuteria",
    "Buty",
    "Czystość",
    "Elektronika",
    "Fastfoody",
    "Inne",
    "Inwestycje",
    "Komunikacja miejska",
    "Makijaż",
    "Mieszkanie",
    "Nauka",
    "Odpoczynek",
    "Paznokcie",
    "Pielęgnacja",
    "Prezenty",
    "Restauracje",
    "Rozrywka",
    "Rzęsy",
    "Samochód",
    "Słodycze",
    "Taksówki",
    "Torebki",
    "Trening",
    "Ubrania",
    "Wakacje",
    "Zakupy spożywcze",
    "Zdrowie"
]

